# Generated by Django 2.1.8 on 2019-07-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liketime',
            field=models.IntegerField(choices=[(1, '1시'), (2, '2시'), (3, '3시'), (4, '4시'), (5, '5시'), (6, '6시'), (7, '7시'), (8, '8시'), (9, '9시'), (10, '10시'), (11, '11시'), (12, '12시'), (13, '13시'), (14, '14시'), (15, '15시'), (16, '16시'), (17, '17시'), (18, '18시'), (19, '19시'), (20, '20시'), (21, '21시'), (22, '22시'), (23, '23시'), (24, '24시')], max_length=2),
        ),
    ]
